export enum AdvertisementType {
    RENT = "FOR_RENT",
    SELL = "FOR_SELL"
}

export enum PropertyType{
    APARTMENT = 'APARTMENT',
    TERRACED_HOUSE = 'TERRACED_HOUSE',
    HOUSE = "HOUSE",
    ROOM = 'ROOM'
}

export enum PropertyCategory{
    FAMILY_HOUSE = "FAMILY_HOUSE",
    SENIOR_HOUSING = "SENIOR_HOUSING",
    YOUTH_HOUSING = 'YOUTH_HOUSING',
    CARE_HOME = 'CARE_HOME'
}

export enum AdditionalInfo {
    BASEMENT = "BASEMENT",
    BALCONY = "BALCONY",
    ELEVATOR = "ELEVATOR",
    OWN_BATH = "OWN_BATH",
    STOVE = 'STOVE',
    OWN_KITCHEN = 'OWN_KITCHEN',
    OWN_TOILET = 'OWN_TOILET',
    REFRIGERATOR = 'REFRIGERATOR',
    PETS_ALLOWED = 'PETS_ALLOWED',
    SHARED_LAUNDRY = 'SHARED_LAUNDRY'
  }